[ -s "$HOME/.profile" ] && . $HOME/.profile
[ -s "$HOME/.bashrc" ] && . $HOME/.bashrc

# Load RVM into a shell session *as a function*
[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"


if [ -z "$SSH_AGENT_PID" ]; then
  keys=$(ls $HOME/.ssh/*id_* | grep -v ':');
  # keychain SSH setup
  if keychain; then 
    keychain $keys
    . "$HOME/.keychain/$HOSTNAME-sh"
  # no keychain? just ssh then?
  else
    eval "ssh-agent -s"
    ssh-add $keys
  fi
fi

# RIP this mechanic
# (note: I added more control to this right before rewriting it all, so if you find it useful, go for it...)
# case $OSTYPE in
#     darwin*)
#         # this is a mac
#     ;;
#     linux*)
#        # this is linux
#        # if we need to detect OS:
#        case $(grep -oP '^NAME="\K[^ "]+' /etc/os-release) in
#           Debian)
#             ;;
#           Arch)
#             ;;
#        esac
#
#        # if we need to detect host system:
#        case "$HOSTNAME" in
#            AXE)
#                ;;
#        esac
#        ;;
#     cygwin)
#         # this is a PC with cygwin
#         PATH="$PATH:/cygdrive/c/Program Files/Oracle/VirtualBox"
#         ;;
#     msys)
#         # this is a PC with msys
#         PATH="$PATH:/mingw/bin:/c/Program Files/Oracle/VirtualBox"
#         ;;
#     *)
#         echo "$OSTYPE not recognized in .bash_profile"
#         ;;
# esac
