#! /bin/bash

if [ "$*" ]; then
	local prompt="$(PS1="$PS1" bash -i <<<$'\nexit' 2>&1 | head -n1)"
	( echo "$(sed 's/\o033\[[0-9]*;[0-9]*m//g'  <<<"$prompt")$@"; exec $@; )
else
	cat
fi | curl -F 'clbin=<-' http://clbin.com


# vim:ft=sh
