#!/bin/bash


SESSION=$1
if ["$SESSION" == ""]; then
  SESSION=$USER
fi

# No TMUX sessions - create
if [ "$(tmux ls $> /dev/null)" != 0 ]
then
  tmux new-session -s "$SESSION"
fi
# One TMUX - resume
tmux attach -t "$SESSION"
