#!/bin/bash
# dumb script that makes it look like you're typing whatever you typed into it
while IFS= read -r -n1 char
do
  # display one character at a time
  echo -n  "$char"
  delay=$(bc <<< "scale=2;$RANDOM/32767")
  sleep $delay
done <<< "$1"
