#!/bin/bash
#
# modified from https://github.com/enkiv2/xkcd-passwords

function rword() {
	cat /usr/share/dict/words | grep -v "'" | sort -R | head -n 1
}
function capitalize() {
	echo $(echo $1 | head -c 1 | tr 'a-z' 'A-Z')$(echo $1 | tail -c +2)
}
w=""
len=4 # default is true to the comic, 6 is recommended
spaces=0
helpp=0
while getopts ":l:sh" opt; do
  case $opt in
    l) len=$OPTARG;;
    s) spaces=1;;
    h|\?)
      echo "-l set length, default is 4, recommended is 6"
      echo "-s insert spaces between words"
      echo "-h display this message"
      helpp=1
      break
      ;;
  esac
done
if [ $helpp -eq 0 ]; then
  if [ $spaces -eq 0 ]; then
    for (( i=1; i<=$len; i++ )); do
      w="$w$(capitalize $(rword))"
    done
  else
    for (( i=1; i<=$len; i++ )); do
      w="$w $(capitalize $(rword))"
    done
  fi
fi

echo $w
